# Generated by Django 4.0.5 on 2022-08-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulCommercialAreaPopErd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.TextField(blank=True, db_column='CD', null=True)),
                ('nm', models.TextField(blank=True, db_column='NM', null=True)),
                ('flpop', models.IntegerField(blank=True, db_column='FLPOP', null=True)),
                ('repop', models.IntegerField(blank=True, db_column='REPOP', null=True)),
                ('wrc_popltn', models.IntegerField(blank=True, db_column='WRC_POPLTN', null=True)),
                ('year', models.BigIntegerField(blank=True, db_column='YEAR', null=True)),
                ('density', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seoul_commercial_area_pop_erd',
                'managed': False,
            },
        ),
    ]
